# Generated by Django 5.0.6 on 2024-07-27 21:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_parceiro', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Detalhes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parceiro_fullname', models.CharField(blank=True, max_length=255)),
                ('parceiro_email', models.CharField(blank=True, max_length=255)),
                ('parceiro_cpf_cnpj', models.CharField(blank=True, max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('estado_civil', models.CharField(max_length=100)),
                ('rg_numero', models.CharField(max_length=20)),
                ('rg_orgexp', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('datanasc', models.DateField()),
                ('celular', models.CharField(max_length=15)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mae', models.CharField(max_length=255)),
                ('pai', models.CharField(max_length=255)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('residencia_estado', models.CharField(max_length=100)),
                ('residencial_cidade', models.CharField(max_length=100)),
                ('classe_profissional', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
                ('valor_patrimonio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pep', models.BooleanField(default=False)),
                ('fatca', models.BooleanField(default=False)),
                ('telefones_adicionais', models.TextField(blank=True)),
                ('telefone_comercial', models.CharField(blank=True, max_length=15)),
                ('nome_referencia', models.CharField(blank=True, max_length=255)),
                ('telefone_referencia', models.CharField(blank=True, max_length=15)),
                ('is_autonomo', models.BooleanField(default=False)),
                ('nome_referencia_comercial', models.CharField(blank=True, max_length=255)),
                ('telefone_referencia_comercial', models.CharField(blank=True, max_length=15)),
                ('valor_financiamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('marca_veiculo', models.CharField(blank=True, max_length=255)),
                ('modelo_veiculo', models.CharField(blank=True, max_length=255)),
                ('ano_fabricacao_veiculo', models.CharField(blank=True, max_length=15)),
                ('placa_veiculo', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
