name: Cromo Backend Production CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker backend image
        uses: docker/build-push-action@v5.0.0
        with: 
          context: ./backend
          file: ./backend/docker/Dockerfile_django
          push: true
          tags: | 
            rbxrobotica/rbx-cro-backend-django-prod:1.0.${{github.run_number}}
            rbxrobotica/rbx-cro-backend-django-prod:latest
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true

      - name: Build and push Docker monolith backend nginx image
        uses: docker/build-push-action@v5.0.0
        with: 
          context: ./backend/
          file: ./backend/docker/Dockerfile_nginx
          push: true
          tags: | 
            rbxrobotica/rbx-cro-backend-nginx-prod:1.0.${{github.run_number}}
            rbxrobotica/rbx-cro-backend-nginx-prod:latest
